### ISSUE TITLE
Create command ‘derafnu-y’

### ISSUE THREAD

**Issue by luizperes** [DestructHub/lelerax-legacy#2]
A command that would do speech-to-text recognition on audio records on Telegram.
The ‘derafnu-y’ would be in mention to @rafaelcn, a guy who’s known for communicating to others strictly through audio waves.
For better understanding: _beautify/debeautify_, _rafnu-y/derafnu-y_. It could also be _rafaelcny/derafaelcny_

**Comment by ryukinix** [comment]
This issue was moved to ryukinix/lelerax#7
