### ISSUE TITLE
Check README

### ISSUE THREAD

**Issue by luizperes** [DestructHub/lelerax-legacy#3]
Check the readme @rafaelcn @ryukinix :P

**Comment by lubien** [comment]
Tem até print meu

**Comment by luizperes** [comment]
Roubei da mídia do grupo @lubien hauha

**Comment by lubien** [comment]
😂

Em ter, 7 de mar de 2017 21:54, Luiz Fernando Peres <
notifications@github.com> escreveu:

**Comment by rafaelcn** [comment]
auheauheahue isso tá muito bom
