### ISSUE TITLE
Create command ‘derafnu-y’

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/lelerax-legacy#7]
_From @luizperes on January 29, 2018 17:5_

A command that would do speech-to-text recognition on audio records on Telegram.
The ‘derafnu-y’ would be in mention to @rafaelcn, a guy who’s known for communicating to others strictly through audio waves.
For better understanding: _beautify/debeautify_, _rafnu-y/derafnu-y_. It could also be _rafaelcny/derafaelcny_

**Comment by rafaelcn** [comment]
I loved this.

**Comment by ryukinix** [comment]
This is useless for now because exists already a similar service called by https://telegram.me/voicybot

**Comment by luizperes** [comment]
we might as well create a bind using `voicybot`, if possible :), otherwise we should just close this issue

**Comment by ryukinix** [comment]
Hm. Closing it's ok, I think. If someone want to CODE that, that person can open this issue again.

**Comment by rafaelcn** [comment]
I think it’s worth to build a back end service to bind to voicybot. As it only takes message with less than 50 seconds and its free engine isn’t that good.

--
Regards,
Rafael Campos Nunes.
rafaelnunes@engineer.com
